comment:
  layout: "reach,diff,flags,tree,betaprofiling"
  show_critical_paths: true
flag_management:
  individual_flags:
    - name: smart-tests
      carryforward: true
      carryforward_mode: "labels"
      statuses:
        - type: "project"
        - type: "patch"
cli:
  plugins:
    pycoverage:
      report_type: "json"